[package]
name = "cozonomono_cozo"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "cozonomono_cozo"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
cozo = "0.7.6"
rustler = "0.30.0"

